---
- hosts: all
  name: playbook run on all nodes
  gather_facts: false
  tasks:
   - name: Add line if it doesn't exists 
     lineinfile:
       path: /home/nitan/test.cfg
       regexp: 'defaults'
       backup: yes
